# Generated by Django 6.0 on 2026-01-04 03:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=10, verbose_name='股票代码')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='当前价格')),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='均价')),
                ('volume', models.IntegerField(verbose_name='成交量')),
                ('timestamp', models.DateTimeField(verbose_name='时间戳')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '股票数据',
                'verbose_name_plural': '股票数据',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=10, verbose_name='股票代码')),
                ('trade_type', models.CharField(choices=[('buy', '买入'), ('sell', '卖出')], max_length=4, verbose_name='交易类型')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='交易价格')),
                ('volume', models.IntegerField(verbose_name='交易数量')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='交易金额')),
                ('reason', models.CharField(max_length=200, verbose_name='交易原因')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='交易时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '交易记录',
                'verbose_name_plural': '交易记录',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TradeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=10, verbose_name='股票代码')),
                ('sell_threshold', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='高于均价卖出阈值(%)')),
                ('buy_threshold', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='低于均价买入阈值(%)')),
                ('update_interval', models.IntegerField(default=5, verbose_name='更新频率(秒)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '交易设置',
                'verbose_name_plural': '交易设置',
            },
        ),
    ]
