# Generated by Django 6.0 on 2026-01-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesetting',
            name='buy_amount',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10, verbose_name='买入金额(元)'),
        ),
        migrations.AddField(
            model_name='tradesetting',
            name='sell_amount',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10, verbose_name='卖出金额(元)'),
        ),
    ]
