# Generated by Django 6.0 on 2026-01-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant', '0002_tradesetting_buy_amount_tradesetting_sell_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesetting',
            name='buy_shares',
            field=models.IntegerField(blank=True, null=True, verbose_name='买入股数(股)'),
        ),
        migrations.AddField(
            model_name='tradesetting',
            name='sell_shares',
            field=models.IntegerField(blank=True, null=True, verbose_name='卖出股数(股)'),
        ),
        migrations.AlterField(
            model_name='tradesetting',
            name='buy_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='买入金额(元)'),
        ),
        migrations.AlterField(
            model_name='tradesetting',
            name='sell_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='卖出金额(元)'),
        ),
    ]
