# Generated by Django 6.0 on 2026-01-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant', '0003_tradesetting_buy_shares_tradesetting_sell_shares_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=10, verbose_name='股票代码')),
                ('balance', models.DecimalField(decimal_places=2, default=100000.0, max_digits=12, verbose_name='账户余额')),
                ('shares', models.IntegerField(default=3000, verbose_name='持股数量')),
                ('available_shares', models.IntegerField(default=3000, verbose_name='可用持股数量（T+1）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '账户信息',
                'verbose_name_plural': '账户信息',
                'unique_together': {('stock_code',)},
            },
        ),
    ]
