# Generated by Django 6.0 on 2026-01-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant', '0004_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesetting',
            name='grid_buy_count',
            field=models.IntegerField(default=1, verbose_name='低于均价格子数买入'),
        ),
        migrations.AddField(
            model_name='tradesetting',
            name='grid_sell_count',
            field=models.IntegerField(default=1, verbose_name='高于均价格子数卖出'),
        ),
        migrations.AddField(
            model_name='tradesetting',
            name='market_stage',
            field=models.CharField(blank=True, choices=[('oscillation', '震荡阶段'), ('downward', '下跌阶段'), ('upward', '上涨阶段')], max_length=20, null=True, verbose_name='行情阶段'),
        ),
        migrations.AddField(
            model_name='tradesetting',
            name='strategy',
            field=models.CharField(choices=[('grid', '格子法做T'), ('percentage', '百分比做T')], default='grid', max_length=20, verbose_name='交易策略'),
        ),
        migrations.AlterField(
            model_name='tradesetting',
            name='buy_threshold',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=5, verbose_name='低于均价买入阈值(%)'),
        ),
        migrations.AlterField(
            model_name='tradesetting',
            name='sell_threshold',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=5, verbose_name='高于均价卖出阈值(%)'),
        ),
    ]
