# Generated by Django 6.0 on 2026-01-25 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant', '0005_tradesetting_grid_buy_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesetting',
            name='overnight_buy_ratio',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='隔夜交易买入比例(%)'),
        ),
        migrations.AddField(
            model_name='tradesetting',
            name='overnight_sell_ratio',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='隔夜交易卖出比例(%)'),
        ),
        migrations.AddField(
            model_name='tradesetting',
            name='pending_loop_type',
            field=models.CharField(blank=True, choices=[('buy_first', '待卖出（买入领先）'), ('sell_first', '待买入（卖出领先）')], max_length=20, null=True, verbose_name='待闭环类型'),
        ),
        migrations.AddField(
            model_name='tradesetting',
            name='pending_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='待闭环价格'),
        ),
        migrations.AddField(
            model_name='tradesetting',
            name='pending_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='待闭环开始时间'),
        ),
        migrations.AddField(
            model_name='tradesetting',
            name='pending_volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='待闭环数量'),
        ),
        migrations.CreateModel(
            name='TradeLoop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=10, verbose_name='股票代码')),
                ('loop_type', models.CharField(choices=[('buy_sell', '买入->卖出'), ('sell_buy', '卖出->买入')], max_length=20, verbose_name='闭环类型')),
                ('is_closed', models.BooleanField(default=False, verbose_name='是否已闭环')),
                ('profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='闭环盈亏')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='闭环时间')),
                ('close_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='close_loops', to='quant.traderecord', verbose_name='平仓记录')),
                ('open_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_loops', to='quant.traderecord', verbose_name='开仓记录')),
            ],
            options={
                'verbose_name': '闭环交易',
                'verbose_name_plural': '闭环交易',
                'ordering': ['-created_at'],
            },
        ),
    ]
