# Generated by Django 6.0 on 2026-01-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant', '0006_tradesetting_overnight_buy_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesetting',
            name='avg_line_range_minus',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=5, verbose_name='均价线左区间(-)'),
        ),
        migrations.AddField(
            model_name='tradesetting',
            name='avg_line_range_plus',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=5, verbose_name='均价线右区间(+)'),
        ),
        migrations.AddField(
            model_name='tradesetting',
            name='oscillation_type',
            field=models.CharField(blank=True, choices=[('low', '低位震荡'), ('normal', '普通震荡')], max_length=20, null=True, verbose_name='震荡类型'),
        ),
    ]
