# Generated by Django 6.0 on 2026-01-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant', '0007_tradesetting_avg_line_range_minus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradesetting',
            name='avg_line_range_minus',
        ),
        migrations.RemoveField(
            model_name='tradesetting',
            name='avg_line_range_plus',
        ),
        migrations.AddField(
            model_name='tradesetting',
            name='buy_avg_line_range_minus',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=5, verbose_name='均价线买入左区间(-)'),
        ),
        migrations.AddField(
            model_name='tradesetting',
            name='buy_avg_line_range_plus',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=5, verbose_name='均价线买入右区间(+)'),
        ),
        migrations.AddField(
            model_name='tradesetting',
            name='sell_avg_line_range_minus',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=5, verbose_name='均价线卖出左区间(-)'),
        ),
        migrations.AddField(
            model_name='tradesetting',
            name='sell_avg_line_range_plus',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=5, verbose_name='均价线卖出右区间(+)'),
        ),
    ]
