# Generated by Django 6.0 on 2026-01-29 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quant', '0008_remove_tradesetting_avg_line_range_minus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradesetting',
            name='buy_amount',
        ),
        migrations.RemoveField(
            model_name='tradesetting',
            name='sell_amount',
        ),
    ]
