# Generated by Django 6.0 on 2026-01-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant', '0009_remove_tradesetting_buy_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradesetting',
            name='buy_avg_line_range_minus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='均价线买入左区间(-)'),
        ),
        migrations.AlterField(
            model_name='tradesetting',
            name='buy_avg_line_range_plus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='均价线买入右区间(+)'),
        ),
        migrations.AlterField(
            model_name='tradesetting',
            name='sell_avg_line_range_minus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='均价线卖出左区间(-)'),
        ),
        migrations.AlterField(
            model_name='tradesetting',
            name='sell_avg_line_range_plus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='均价线卖出右区间(+)'),
        ),
    ]
