# Generated by Django 6.0 on 2026-01-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant', '0010_alter_tradesetting_buy_avg_line_range_minus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradesetting',
            name='is_executing',
            field=models.BooleanField(default=False, verbose_name='是否正在执行交易'),
        ),
    ]
