# Generated by Django 6.0 on 2026-01-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant', '0011_tradesetting_is_executing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradesetting',
            name='grid_buy_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='低于均价格子数买入'),
        ),
        migrations.AlterField(
            model_name='tradesetting',
            name='grid_sell_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='高于均价格子数卖出'),
        ),
    ]
