# Generated by Django 6.0 on 2026-01-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant', '0012_alter_tradesetting_grid_buy_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradesetting',
            name='stock_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='股票代码'),
        ),
    ]
