# Generated by Django 6.0.2 on 2026-02-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant', '0013_alter_tradesetting_stock_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradesetting',
            name='strategy',
            field=models.CharField(choices=[('grid', '格子法做T'), ('percentage', '百分比做T'), ('multi_factor', '多因子做T')], default='multi_factor', max_length=20, verbose_name='交易策略'),
        ),
    ]
