# Generated by Django 6.0.2 on 2026-02-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant', '0014_alter_tradesetting_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradesetting',
            name='buy_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.5, max_digits=5, null=True, verbose_name='低于均价买入阈值(%)'),
        ),
        migrations.AlterField(
            model_name='tradesetting',
            name='sell_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.5, max_digits=5, null=True, verbose_name='高于均价卖出阈值(%)'),
        ),
    ]
